"""initial migration

Revision ID: 64c416aee859
Revises:
Create Date: 2026-05-09 18:44:11.841393

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64c416aee859"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("game_type", sa.String(), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.create_index(
            "idx_games_data_players",
            [sa.literal_column("(data -> 'players')")],  # type: ignore
            unique=False,
            postgresql_using="gin",
        )
        batch_op.create_index(batch_op.f("ix_games_date"), ["date"], unique=False)

    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("encrypted_password", sa.String(), nullable=False),
        sa.Column("last_scraped_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_games_date"))
        batch_op.drop_index("idx_games_data_players", postgresql_using="gin")

    op.drop_table("games")
    # ### end Alembic commands ###
